server:
  port: 8100
  max-http-request-header-size: 500KB
  tomcat:
    connection-timeout: 70000
spring:
  profiles:
    active: '@profiles.active@'
  application:
    name: core-backend
  messages:
    encoding: UTF-8
  main:
    allow-circular-references: true
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache/ehcache.xml
  data:
    redis:
      host: 172.18.207.71
      port: 6379
      database: 0
      password: testredis@123#
  jackson:
    parser:
      allow-numeric-leading-zeros: true
management:
  health:
    redis:
      enabled: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    path: /opt/dataease2.0/logs/dataease
# sql日志生产环境注释掉
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

quartz:
  enabled: true
  scheduler-name: deSyncJob

dataease:
  version: '@project.version@'
  xpack-front-distributed: true
  origin-list: http://192.168.1.9:9080
  apisix-api:
    domain: http://192.168.1.9:9180
    key: edd1c9f034335f136f87ad84b625c8f1

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: false

module.auth.redis:
  client-name: aciga-auth
  host: 172.18.207.71
  port: 6379
  password: testredis@123#
  database: 0
  lettuce.pool.enabled: true
  lettuce.pool.max-active: 1
  timeout: 1000

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: xtoken
  # jwt秘钥
  jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk
  # token有效期，单位s 默认30天, -1代表永不过期（7天）
  timeout: 604800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 3600
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: jwt
  # 是否输出操作日志
  is-log: true
